# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.17/Modules/CMakeCInformation.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.17/Modules/CMakeCXXInformation.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.17/Modules/CMakeCheckCompilerFlagCommonPatterns.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.17/Modules/CMakeCommonLanguageInclude.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.17/Modules/CMakeGenericSystem.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.17/Modules/CMakeInitializeConfigs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.17/Modules/CMakeLanguageInformation.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.17/Modules/CMakeSystemSpecificInformation.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.17/Modules/CMakeSystemSpecificInitialize.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.17/Modules/CheckCXXCompilerFlag.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.17/Modules/CheckCXXSourceCompiles.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.17/Modules/Compiler/AppleClang-C.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.17/Modules/Compiler/AppleClang-CXX.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.17/Modules/Compiler/CMakeCommonCompilerMacros.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.17/Modules/Compiler/Clang.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.17/Modules/Compiler/GNU.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.17/Modules/Internal/CMakeCheckCompilerFlag.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.17/Modules/Platform/Apple-AppleClang-C.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.17/Modules/Platform/Apple-AppleClang-CXX.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.17/Modules/Platform/Apple-Clang-C.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.17/Modules/Platform/Apple-Clang-CXX.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.17/Modules/Platform/Apple-Clang.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.17/Modules/Platform/Darwin-Initialize.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.17/Modules/Platform/Darwin.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.17/Modules/Platform/UnixPaths.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/yinyinlu/OneDrive\ -\ University\ of\ Toronto/Projects/ComputerGraphic/computer-graphics-raster-images/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/yinyinlu/OneDrive\ -\ University\ of\ Toronto/Projects/ComputerGraphic/computer-graphics-raster-images/xcodeBuild/CMakeFiles/3.17.2/CMakeCCompiler.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/yinyinlu/OneDrive\ -\ University\ of\ Toronto/Projects/ComputerGraphic/computer-graphics-raster-images/xcodeBuild/CMakeFiles/3.17.2/CMakeCXXCompiler.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/yinyinlu/OneDrive\ -\ University\ of\ Toronto/Projects/ComputerGraphic/computer-graphics-raster-images/xcodeBuild/CMakeFiles/3.17.2/CMakeSystem.cmake))

/Users/yinyinlu/OneDrive\ -\ University\ of\ Toronto/Projects/ComputerGraphic/computer-graphics-raster-images/xcodeBuild/CMakeFiles/cmake.check_cache: $(TARGETS)
	/Applications/CMake.app/Contents/bin/cmake -H/Users/yinyinlu/OneDrive\ -\ University\ of\ Toronto/Projects/ComputerGraphic/computer-graphics-raster-images -B/Users/yinyinlu/OneDrive\ -\ University\ of\ Toronto/Projects/ComputerGraphic/computer-graphics-raster-images/xcodeBuild
